spring:
  datasource:
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_2010_mybatis?characterEncoding=utf-8
    username: root
    password: admin123
mybatis:
  type-aliases-package: com.qfedu.springboot.ssm.beans
  mapper-locations: classpath:mappers/*.xml
