spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fmmall?characterEncoding=utf-8
      username: root
      password: admin123
  redis:
    port: 6379
    host: 43.142.17.246
    database: 0
    password: admin123
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.qfedu.fmmall.entity
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
